### ISSUE TITLE
Liveliness probe check fails with 401 in Kubernetes using Helm chart

### ISSUE THREAD

**Issue by HerveZu** [SimonSchneider/traefik-jwt-decode#42]
Helm repository : `https://athics-team.github.io/traefik-jwt-decode/`
Helm chart : `traefik-jwt-decode`
Helm version : `0.1.0`
Helm values
```yml
replicaCount: 1
service:
  port: 8080
env:
  PORT: 8080
  AUTH_HEADER_REQUIRED: "true"
  JWKS_URL: https://myauth0tenant.auth0.com/.well-known/jwks.json
```
When deploying to my Kubernetes cluster, the liveliness probe check fails (401). I looked at the configuration and the probe checks (both liveliness and readiness) were not set to use `/ping` but the default `/` instead, despite the configuration in [this file](https://github.com/SimonSchneider/traefik-jwt-decode/blob/master/_helm/traefik-jwt-decode/templates/deployment.yaml).

Do you have any idea of how to fix this ?
